name: monix_assets
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_lints: ^2.0.1
  build_runner:
  flutter_gen_runner:

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true

  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true
      class_name: MonixAssets

  fonts:
    enabled: false
  colors:
    enabled: false

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
