// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA618y6LeLB7p4ORW7DuBT5X3wVpnbUxxg',
    appId: '1:305549396589:web:24f97e2a63c77a1944cd64',
    messagingSenderId: '305549396589',
    projectId: 'monixai-78b0a',
    authDomain: 'monixai-78b0a.firebaseapp.com',
    storageBucket: 'monixai-78b0a.appspot.com',
    measurementId: 'G-B1LQTT6GQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo2gYET58VsZGTalwqUS94lSt9M_oGzXg',
    appId: '1:305549396589:android:5b5ca397053bfa1544cd64',
    messagingSenderId: '305549396589',
    projectId: 'monixai-78b0a',
    storageBucket: 'monixai-78b0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN1Kg1oLdGq8BuEjDjpufuLNnZjnOcV7k',
    appId: '1:305549396589:ios:9953f07a04af9e3c44cd64',
    messagingSenderId: '305549396589',
    projectId: 'monixai-78b0a',
    storageBucket: 'monixai-78b0a.appspot.com',
    iosBundleId: 'com.monix.monix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN1Kg1oLdGq8BuEjDjpufuLNnZjnOcV7k',
    appId: '1:305549396589:ios:9953f07a04af9e3c44cd64',
    messagingSenderId: '305549396589',
    projectId: 'monixai-78b0a',
    storageBucket: 'monixai-78b0a.appspot.com',
    iosBundleId: 'com.monix.monix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA618y6LeLB7p4ORW7DuBT5X3wVpnbUxxg',
    appId: '1:305549396589:web:325e657efc6b6cb044cd64',
    messagingSenderId: '305549396589',
    projectId: 'monixai-78b0a',
    authDomain: 'monixai-78b0a.firebaseapp.com',
    storageBucket: 'monixai-78b0a.appspot.com',
    measurementId: 'G-CNFRDVB1X8',
  );
}
