name: network
description: Monix Network call handle

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  common:
    path: ../common

  dio: ^5.1.2
  flutter_riverpod: ^2.1.1
  freezed_annotation: ^2.2.0
  equatable: ^2.0.5
  json_annotation: ^4.7.0
  easy_localization: ^3.0.1
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.2.1
  http_parser: ^4.0.2
  google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  json_serializable: ^6.5.4
  build_runner: ^2.3.2
  freezed: ^2.2.1
  flutter_gen_runner: ^5.1.0+1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true