name: common
description: A new Flutter package project.
version: 0.0.1


environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  monix_assets:
    path: ../monix_assets

  dimensions_theme: ^0.1.1
  flutter_screenutil: ^5.9.3
  go_router: ^14.1.4
  flutter_spinkit: ^5.2.1
  fluttertoast: ^8.2.6
  image_cropper: ^6.0.0
  image_picker: ^1.1.2
  flutter_riverpod: ^2.5.1
  file_picker: ^8.0.3
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true


  fonts:
    - family: Sofia Pro
      fonts:
        - asset: assets/fonts/Sofia Pro Bold.ttf
          weight: 700
        - asset: assets/fonts/Sofia Pro Light.ttf
          weight: 300
        - asset: assets/fonts/Sofia Pro Regular.ttf
          weight: 400
        - asset: assets/fonts/Sofia Pro Medium.ttf
          weight: 500
        - asset: assets/fonts/Sofia Pro Semi Bold.ttf
          weight: 600
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

